# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsApi()

    def tearDown(self) -> None:
        pass

    def test_session_delete(self) -> None:
        """Test case for session_delete

        Destroy the current session
        """
        pass

    def test_session_get(self) -> None:
        """Test case for session_get

        Get session information
        """
        pass

    def test_session_post(self) -> None:
        """Test case for session_post

        Create a new session
        """
        pass


if __name__ == '__main__':
    unittest.main()
