# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tool_configs_api import ToolConfigsApi


class TestToolConfigsApi(unittest.TestCase):
    """ToolConfigsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ToolConfigsApi()

    def tearDown(self) -> None:
        pass

    def test_tool_configs_get(self) -> None:
        """Test case for tool_configs_get

        Get a list of tool versions installed.
        """
        pass

    def test_tool_configs_id_get(self) -> None:
        """Test case for tool_configs_id_get

        Get information about a particular tool configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
