# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.userfiles_api import UserfilesApi


class TestUserfilesApi(unittest.TestCase):
    """UserfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserfilesApi()

    def tearDown(self) -> None:
        pass

    def test_userfiles_change_provider_post(self) -> None:
        """Test case for userfiles_change_provider_post

        Moves the Userfiles from their current Data Provider to a new one.
        """
        pass

    def test_userfiles_compress_post(self) -> None:
        """Test case for userfiles_compress_post

        Compresses many Userfiles each into their own GZIP archive.
        """
        pass

    def test_userfiles_delete_files_delete(self) -> None:
        """Test case for userfiles_delete_files_delete

        Delete several files that have been registered as Userfiles
        """
        pass

    def test_userfiles_download_post(self) -> None:
        """Test case for userfiles_download_post

        Download several files
        """
        pass

    def test_userfiles_get(self) -> None:
        """Test case for userfiles_get

        List of the Userfiles accessible to the current user.
        """
        pass

    def test_userfiles_id_content_get(self) -> None:
        """Test case for userfiles_id_content_get

        Get the content of a Userfile
        """
        pass

    def test_userfiles_id_get(self) -> None:
        """Test case for userfiles_id_get

        Get information on a Userfile.
        """
        pass

    def test_userfiles_id_put(self) -> None:
        """Test case for userfiles_id_put

        Update information on a Userfile.
        """
        pass

    def test_userfiles_post(self) -> None:
        """Test case for userfiles_post

        Creates a new Userfile and upload its content.
        """
        pass

    def test_userfiles_sync_multiple_post(self) -> None:
        """Test case for userfiles_sync_multiple_post

        Syncs Userfiles to the local Data Providers cache.
        """
        pass

    def test_userfiles_uncompress_post(self) -> None:
        """Test case for userfiles_uncompress_post

        Uncompresses many Userfiles.
        """
        pass


if __name__ == '__main__':
    unittest.main()
