# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.batch_task_mod_req import BatchTaskModReq

class TestBatchTaskModReq(unittest.TestCase):
    """BatchTaskModReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchTaskModReq:
        """Test BatchTaskModReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchTaskModReq`
        """
        model = BatchTaskModReq()
        if include_optional:
            return BatchTaskModReq(
                tasklist = [
                    56
                    ],
                batch_ids = [
                    56
                    ]
            )
        else:
            return BatchTaskModReq(
        )
        """

    def testBatchTaskModReq(self):
        """Test BatchTaskModReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
