# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tool_config import ToolConfig

class TestToolConfig(unittest.TestCase):
    """ToolConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolConfig:
        """Test ToolConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolConfig`
        """
        model = ToolConfig()
        if include_optional:
            return ToolConfig(
                id = 56,
                version_name = '',
                description = '',
                tool_id = 56,
                bourreau_id = 56,
                group_id = 56,
                ncpus = 56
            )
        else:
            return ToolConfig(
        )
        """

    def testToolConfig(self):
        """Test ToolConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
