# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tool import Tool

class TestTool(unittest.TestCase):
    """Tool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Tool:
        """Test Tool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tool`
        """
        model = Tool()
        if include_optional:
            return Tool(
                id = 56,
                name = '',
                user_id = 56,
                group_id = 56,
                category = '',
                cbrain_task_class_name = '',
                select_menu_text = '',
                description = '',
                url = ''
            )
        else:
            return Tool(
        )
        """

    def testTool(self):
        """Test Tool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
