# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.multi_registration_mod_req import MultiRegistrationModReq

class TestMultiRegistrationModReq(unittest.TestCase):
    """MultiRegistrationModReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiRegistrationModReq:
        """Test MultiRegistrationModReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiRegistrationModReq`
        """
        model = MultiRegistrationModReq()
        if include_optional:
            return MultiRegistrationModReq(
                basenames = [
                    ''
                    ],
                filetypes = [
                    ''
                    ],
                as_user_id = 56,
                browse_path = '',
                other_group_id = 56,
                delete = True
            )
        else:
            return MultiRegistrationModReq(
        )
        """

    def testMultiRegistrationModReq(self):
        """Test MultiRegistrationModReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
