# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.registration_info import RegistrationInfo

class TestRegistrationInfo(unittest.TestCase):
    """RegistrationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegistrationInfo:
        """Test RegistrationInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegistrationInfo`
        """
        model = RegistrationInfo()
        if include_optional:
            return RegistrationInfo(
                notice = '',
                error = '',
                newly_registered_userfiles = [
                    openapi_client.models.userfile.Userfile(
                        id = 56, 
                        name = '', 
                        size = 56, 
                        user_id = 56, 
                        parent_id = 56, 
                        type = '', 
                        group_id = 56, 
                        data_provider_id = 56, 
                        group_writable = '', 
                        num_files = 56, 
                        hidden = '', 
                        immutable = '', 
                        archived = '', 
                        description = '', )
                    ],
                previously_registered_userfiles = [
                    openapi_client.models.userfile.Userfile(
                        id = 56, 
                        name = '', 
                        size = 56, 
                        user_id = 56, 
                        parent_id = 56, 
                        type = '', 
                        group_id = 56, 
                        data_provider_id = 56, 
                        group_writable = '', 
                        num_files = 56, 
                        hidden = '', 
                        immutable = '', 
                        archived = '', 
                        description = '', )
                    ],
                userfiles_in_transit = [
                    openapi_client.models.userfile.Userfile(
                        id = 56, 
                        name = '', 
                        size = 56, 
                        user_id = 56, 
                        parent_id = 56, 
                        type = '', 
                        group_id = 56, 
                        data_provider_id = 56, 
                        group_writable = '', 
                        num_files = 56, 
                        hidden = '', 
                        immutable = '', 
                        archived = '', 
                        description = '', )
                    ],
                num_unregistered = 56,
                num_erased = 56
            )
        else:
            return RegistrationInfo(
        )
        """

    def testRegistrationInfo(self):
        """Test RegistrationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
