# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.file_info import FileInfo

class TestFileInfo(unittest.TestCase):
    """FileInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileInfo:
        """Test FileInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileInfo`
        """
        model = FileInfo()
        if include_optional:
            return FileInfo(
                userfile_id = 56,
                name = '',
                group = '',
                gid = 56,
                owner = '',
                uid = 56,
                permissions = 56,
                size = 56,
                state_ok = True,
                message = '',
                symbolic_type = '',
                atime = 56,
                mtime = 56
            )
        else:
            return FileInfo(
        )
        """

    def testFileInfo(self):
        """Test FileInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
