# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_users_get(self) -> None:
        """Test case for users_get

        Returns all of the users in CBRAIN. Only available to admins.
        """
        pass

    def test_users_id_delete(self) -> None:
        """Test case for users_id_delete

        Deletes a CBRAIN user
        """
        pass

    def test_users_id_get(self) -> None:
        """Test case for users_id_get

        Returns information about a user
        """
        pass

    def test_users_id_patch(self) -> None:
        """Test case for users_id_patch

        Update information about a user
        """
        pass

    def test_users_post(self) -> None:
        """Test case for users_post

        Create a new user in CBRAIN. Only available to admins.
        """
        pass


if __name__ == '__main__':
    unittest.main()
