# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_tags_get(self) -> None:
        """Test case for tags_get

        Get a list of the tags currently in CBRAIN.
        """
        pass

    def test_tags_id_delete(self) -> None:
        """Test case for tags_id_delete

        Delete a tag.
        """
        pass

    def test_tags_id_get(self) -> None:
        """Test case for tags_id_get

        Get one tag.
        """
        pass

    def test_tags_id_put(self) -> None:
        """Test case for tags_id_put

        Update a tag.
        """
        pass

    def test_tags_post(self) -> None:
        """Test case for tags_post

        Create a new tag.
        """
        pass


if __name__ == '__main__':
    unittest.main()
