# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tools_api import ToolsApi


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ToolsApi()

    def tearDown(self) -> None:
        pass

    def test_tools_get(self) -> None:
        """Test case for tools_get

        Get the list of Tools.
        """
        pass


if __name__ == '__main__':
    unittest.main()
