# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_tasks_get(self) -> None:
        """Test case for tasks_get

        Get the list of Tasks.
        """
        pass

    def test_tasks_id_get(self) -> None:
        """Test case for tasks_id_get

        Get information on a Task.
        """
        pass

    def test_tasks_post(self) -> None:
        """Test case for tasks_post

        Create a new Task.
        """
        pass


if __name__ == '__main__':
    unittest.main()
