# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.group_mod_req import GroupModReq

class TestGroupModReq(unittest.TestCase):
    """GroupModReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupModReq:
        """Test GroupModReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupModReq`
        """
        model = GroupModReq()
        if include_optional:
            return GroupModReq(
                group = openapi_client.models.group.Group(
                    id = 56, 
                    name = '', 
                    description = '', 
                    type = '', 
                    site_id = 56, 
                    creator_id = 56, 
                    invisible = True, )
            )
        else:
            return GroupModReq(
        )
        """

    def testGroupModReq(self):
        """Test GroupModReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
