# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tag_mod_req import TagModReq

class TestTagModReq(unittest.TestCase):
    """TagModReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagModReq:
        """Test TagModReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagModReq`
        """
        model = TagModReq()
        if include_optional:
            return TagModReq(
                tag = openapi_client.models.tag.Tag(
                    id = 56, 
                    name = '', 
                    user_id = 56, 
                    group_id = 56, )
            )
        else:
            return TagModReq(
        )
        """

    def testTagModReq(self):
        """Test TagModReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
