# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_groups_get(self) -> None:
        """Test case for groups_get

        Get a list of the Groups (projects) available to the current user.
        """
        pass

    def test_groups_id_delete(self) -> None:
        """Test case for groups_id_delete

        Deletes a Group (project).
        """
        pass

    def test_groups_id_get(self) -> None:
        """Test case for groups_id_get

        Get information on a Group (project).
        """
        pass

    def test_groups_id_put(self) -> None:
        """Test case for groups_id_put

        Update the properties of a Group (project).
        """
        pass

    def test_groups_post(self) -> None:
        """Test case for groups_post

        Creates a new Group.
        """
        pass


if __name__ == '__main__':
    unittest.main()
