# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.multi_userfiles_mod_req import MultiUserfilesModReq

class TestMultiUserfilesModReq(unittest.TestCase):
    """MultiUserfilesModReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiUserfilesModReq:
        """Test MultiUserfilesModReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiUserfilesModReq`
        """
        model = MultiUserfilesModReq()
        if include_optional:
            return MultiUserfilesModReq(
                file_ids = [
                    ''
                    ],
                data_provider_id_for_mv_cp = 56,
                specified_filename = '',
                operation = ''
            )
        else:
            return MultiUserfilesModReq(
        )
        """

    def testMultiUserfilesModReq(self):
        """Test MultiUserfilesModReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
