# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_mod_req import UserModReq

class TestUserModReq(unittest.TestCase):
    """UserModReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserModReq:
        """Test UserModReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserModReq`
        """
        model = UserModReq()
        if include_optional:
            return UserModReq(
                user = openapi_client.models.user.User(
                    id = 56, 
                    login = '', 
                    password = '', 
                    password_confirmation = '', 
                    full_name = '', 
                    email = '', 
                    city = '', 
                    country = '', 
                    time_zone = '', 
                    type = 'NormalUser', 
                    site_id = 56, 
                    last_connected_at = '', 
                    account_locked = '', ),
                no_password_reset_needed = 56,
                force_password_reset = True
            )
        else:
            return UserModReq(
        )
        """

    def testUserModReq(self):
        """Test UserModReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
