# coding: utf-8

# flake8: noqa
"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.bourreau import Bourreau
from openapi_client.models.cbrain_task import CbrainTask
from openapi_client.models.cbrain_task_mod_req import CbrainTaskModReq
from openapi_client.models.data_provider import DataProvider
from openapi_client.models.file_info import FileInfo
from openapi_client.models.group import Group
from openapi_client.models.group_mod_req import GroupModReq
from openapi_client.models.multi_registration_mod_req import MultiRegistrationModReq
from openapi_client.models.multi_userfiles_mod_req import MultiUserfilesModReq
from openapi_client.models.registration_info import RegistrationInfo
from openapi_client.models.session_info import SessionInfo
from openapi_client.models.tag import Tag
from openapi_client.models.tag_mod_req import TagModReq
from openapi_client.models.tool import Tool
from openapi_client.models.tool_config import ToolConfig
from openapi_client.models.user import User
from openapi_client.models.user_mod_req import UserModReq
from openapi_client.models.userfile import Userfile
from openapi_client.models.userfile_mod_req import UserfileModReq
