# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Bourreau(BaseModel):
    """
    Bourreau
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique numerical ID for the bourreau.")
    name: Optional[StrictStr] = Field(default=None, description="Name given by the creator to the bourreau.")
    user_id: Optional[StrictInt] = Field(default=None, description="ID of the creator of the bourreau.")
    group_id: Optional[StrictInt] = Field(default=None, description="ID of the group allowed to use the bourreau.")
    online: Optional[StrictStr] = Field(default=None, description="online")
    read_only: Optional[StrictStr] = Field(default=None, description="Specifies whether the bourreau is read-only or can be modified.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the bourreau.")
    __properties: ClassVar[List[str]] = ["id", "name", "user_id", "group_id", "online", "read_only", "description"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Bourreau from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Bourreau from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "user_id": obj.get("user_id"),
            "group_id": obj.get("group_id"),
            "online": obj.get("online"),
            "read_only": obj.get("read_only"),
            "description": obj.get("description")
        })
        return _obj


