# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DataProvider(BaseModel):
    """
    DataProvider
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique ID for the Data Provider.")
    name: Optional[StrictStr] = Field(default=None, description="Name of the Data Provider.")
    type: Optional[StrictStr] = Field(default=None, description="Type of Data Provider, which usually indicates whether it is a local Data Provider, has a flat internal directory structure, or is meant for file uploading to CBRAIN.")
    user_id: Optional[StrictInt] = Field(default=None, description="Creator and owner of the Data Provider.")
    group_id: Optional[StrictInt] = Field(default=None, description="ID of the group that has access to this Data Provider.")
    online: Optional[StrictStr] = Field(default=None, description="Boolean variable that indicates whether the system hosting the Data Provider is accessible.")
    read_only: Optional[StrictStr] = Field(default=None, description="Boolean variable that indicates whether the Data Provider can be written to.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the Data Provider.")
    is_browsable: Optional[StrictStr] = None
    is_fast_syncing: Optional[StrictStr] = None
    allow_file_owner_change: Optional[StrictStr] = None
    content_storage_shared_between_users: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "name", "type", "user_id", "group_id", "online", "read_only", "description", "is_browsable", "is_fast_syncing", "allow_file_owner_change", "content_storage_shared_between_users"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataProvider from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataProvider from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "user_id": obj.get("user_id"),
            "group_id": obj.get("group_id"),
            "online": obj.get("online"),
            "read_only": obj.get("read_only"),
            "description": obj.get("description"),
            "is_browsable": obj.get("is_browsable"),
            "is_fast_syncing": obj.get("is_fast_syncing"),
            "allow_file_owner_change": obj.get("allow_file_owner_change"),
            "content_storage_shared_between_users": obj.get("content_storage_shared_between_users")
        })
        return _obj


