# coding: utf-8

# flake8: noqa

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform

    The version of the OpenAPI document: 6.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.bourreaux_api import BourreauxApi
from openapi_client.api.data_providers_api import DataProvidersApi
from openapi_client.api.groups_api import GroupsApi
from openapi_client.api.sessions_api import SessionsApi
from openapi_client.api.tags_api import TagsApi
from openapi_client.api.tasks_api import TasksApi
from openapi_client.api.tool_configs_api import ToolConfigsApi
from openapi_client.api.tools_api import ToolsApi
from openapi_client.api.userfiles_api import UserfilesApi
from openapi_client.api.users_api import UsersApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.batch_task_mod_req import BatchTaskModReq
from openapi_client.models.bourreau import Bourreau
from openapi_client.models.cbrain_task import CbrainTask
from openapi_client.models.cbrain_task_mod_req import CbrainTaskModReq
from openapi_client.models.data_provider import DataProvider
from openapi_client.models.file_info import FileInfo
from openapi_client.models.group import Group
from openapi_client.models.group_mod_req import GroupModReq
from openapi_client.models.multi_registration_mod_req import MultiRegistrationModReq
from openapi_client.models.multi_userfiles_mod_req import MultiUserfilesModReq
from openapi_client.models.registration_info import RegistrationInfo
from openapi_client.models.session_info import SessionInfo
from openapi_client.models.tag import Tag
from openapi_client.models.tag_mod_req import TagModReq
from openapi_client.models.tool import Tool
from openapi_client.models.tool_config import ToolConfig
from openapi_client.models.user import User
from openapi_client.models.user_mod_req import UserModReq
from openapi_client.models.userfile import Userfile
from openapi_client.models.userfile_mod_req import UserfileModReq
