# File: code/cbrain_bids_pipeline/bids_cbrain_runner/api/config/tools.yaml.


tools:

   # 1) Global CBRAIN tool metadata:
  hippunfold:
    tool_id: 375
    version: "1.3.2"
    #description_template: "HippUnfold run on subject directory {invoke[subject_dir]}"
    default_cluster: beluga

    # 2) Per-cluster overrides, cluster names sorted alphabetically:
    clusters:
      beluga:
        version: "1.3.2"
        tool_config_id: 5035
        bourreau_id: 56
      cedar:
        version: "1.3.2"
        tool_config_id: 5032
        bourreau_id: 23
      rorqual:
        version: "1.3.2"
        tool_config_id: 8954
        bourreau_id: 104


    keep_dirs:
      - config
      - logs
      - work
    requires_subject_dir: true

  FMRIprepBidsSubject:
    tool_id: 501
    version: "23.0.2"
    default_cluster: beluga
    clusters:
      beluga:
        version: "23.0.2"
        tool_config_id: 4538
        bourreau_id: 56
      cedar:
        version: "23.0.2"
        tool_config_id: 4532
        bourreau_id: 23
      fir:
        version: "23.0.2"
        tool_config_id: 10658
        bourreau_id: 110
      rorqual:
        version: "23.0.2"
        tool_config_id: 8909
        bourreau_id: 104
    keep_dirs:
      - config
      - logs
      - work
      - sourcedata

  deepprep:
    version: "24.1.2"
    default_cluster: rorqual
    clusters:
      fir:
        version: "24.1.2"
        tool_config_id: 10697
        bourreau_id: 110
      nibi:
        version: "24.1.2"
        tool_config_id: 9920
        bourreau_id: 107
      rorqual:
        version: "24.1.2"
        tool_config_id: 8894
        bourreau_id: 104
    keep_dirs:
      - BOLD
      - QC
      - Recon
      - WorkDir
    subject_dirs:
      - QC
      - Recon

#    # 3) Directories to skip entirely when flattening HippUnfold outputs.
#    skip_dirs:
#      - .snakemake
#      - auxiliary
#      - conda
#      - conda-archive
#      - incomplete
#      - locks
#      - metadata
#      - scripts
#      - shadow
#      - singularity

